services:

  postgres:
    image: postgres:14-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/auth_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SECRET_KEY=pSdb7zAnuK8Xbi2kljQks0+rr2OxLJjHJ8Gc+EfrqDp9MN4LXw==
    ports:
      - "8080:8080"
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  postgres-data: